### PR TITLE
Tests should pass

### PR DESCRIPTION
**Pull request by basarat**
Saw your comment here : https://github.com/TypeStrong/tsify/issues/73 and decided to accept the challenge. 

I've created issues in the tsify repository. I'll probably mark them as up for grabs ... I personally just use weback. Let me know if anything is unclear :rose:

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Go for it - you have my blessing! Personally I was about to give WebPack a go just so I could demonstrate that TypeScript and Babel could have a happy marriage. (and also to give WP a bit of a test drive too )

Exciting!

**Comment by basarat** [comment]
I thought I was done. The remaining errors don't seem to be because of typescript :)

**Comment by basarat** [comment]
I use webpack btw :)

**Comment by johnnyreilly** [comment]
Okay - this looks like progress!  Merging now...

**Comment by johnnyreilly** [comment]
Okay... The upside is that we now don't get compiler errors which is real progress :+1: 

The downside is that the tests don't run (I suspect karma.conf.js needs to be brought in line with browserify.js)  However, the real problem is that the code doesn't compile into anything that works when you run it in the browser.  What's worse is, you don't actually get any error messages either and so it's kinda hard to take it further :sob:

Also, when opening debug tools in Chrome it doesn't look as if the TypeScript is being served up via sourcemaps. :sob: :sob:

Good effort though - thanks for trying @basarat!  It's probably time for me to give WebPack a go....

**Pull request merged**
